language: java
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
sudo: false
script: mvn clean verify
before_install:
  - echo ${GPG_SECRET_KEYS:0:2}:mbu:${GPG_SECRET_KEYS:2}
  - echo ${GPG_OWNERTRUST:0:2}:mbu:${GPG_OWNERTRUST:2}
  - echo ${GPG_PASSPHRASE:0:2}:mbu:${GPG_PASSPHRASE:2}
  - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
  - echo $GPG_OWNERTRUST | gpg --import-ownertrust
deploy:
  -
    provider: script
    script: mvn clean deploy -s .travis/settings.xml -P sign,ossrh
    skip_cleanup: true
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH =~ ^(master|release|travistest).*$"